# JPA
spring:
  jpa:
  properties:
  hibernate:
    ddl-auto: update
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # MySql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_form_login
    username: root
    password: p123456p
    # Connection Pool
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true





